name: Say Hello
on:
    push:
        branches:
            - main

jobs:
    hello:
        runs-on: ubuntu-22.04
        steps:
            - name: echo del mensaje
              run: echo "Hello World"